/**
 * Public identity of the site, for the places that need an ABSOLUTE URL.
 *
 * Open Graph and Twitter only accept absolute image URLs — a relative
 * `/og.png` is silently dropped by most crawlers — so the canonical public
 * origin has to be a constant that ships in the HTML head. It cannot come from
 * `siteOrigin()` in `src/server/auth-core.ts`: that helper reads request
 * headers and `process.env`, i.e. it is server-only, while `__root.tsx` head
 * is shared client/server code.
 *
 * This is the owner's own domain (the bare domain redirects to www), so a
 * preview deployment also advertises the live card. That is deliberate: the
 * card is only ever fetched by crawlers scraping the public site, and pointing
 * previews at their own hostnames would leak sandbox hosts into share cards.
 */
export const SITE_ORIGIN = "https://www.imechanic.app";

/** 1200x630 share card, generated by `bun scripts/gen-og.mjs` (M1). */
export const OG_IMAGE_PATH = "/og.png";
export const OG_IMAGE_URL = `${SITE_ORIGIN}${OG_IMAGE_PATH}`;
export const OG_IMAGE_WIDTH = "1200";
export const OG_IMAGE_HEIGHT = "630";

/** What the card actually shows — the alt text crawlers and readers get. */
export const OG_IMAGE_ALT =
  "iMechanic — from fault code to completed repair. The three severity verdicts: drive on, repair soon, stop driving.";
