import { HeadContent, Outlet, Scripts, createRootRoute } from "@tanstack/react-router";
import { useEffect } from "react";
import type { ReactNode } from "react";
import {
  OG_IMAGE_ALT,
  OG_IMAGE_HEIGHT,
  OG_IMAGE_URL,
  OG_IMAGE_WIDTH,
  SITE_ORIGIN,
} from "~/lib/site";
import { themeInitScript, themeDataAttrs } from "~/lib/theme";
import appCss from "~/styles/app.css?url";

export const Route = createRootRoute({
  head: () => ({
    meta: [
      { charSet: "utf-8" },
      { name: "viewport", content: "width=device-width, initial-scale=1" },
      {
        title: "iMechanic — From fault code to completed repair",
      },
      {
        name: "description",
        content:
          "iMechanic takes you from a check-engine light to a completed, affordable repair: AI root-cause diagnosis, an honest severity verdict, and a DIY-vs-workshop cost decision. Reading codes and clearing them is free, always.",
      },
      /* Navy chrome in the light theme; the dark app background in the dark
         theme, so the installed PWA's system bars match what's on screen. */
      {
        name: "theme-color",
        media: "(prefers-color-scheme: light)",
        content: "#0b1220",
      },
      {
        name: "theme-color",
        media: "(prefers-color-scheme: dark)",
        content: "#070d18",
      },
      { property: "og:title", content: "iMechanic — From fault code to completed repair" },
      {
        property: "og:description",
        content:
          "AI root-cause diagnosis, an honest severity verdict, a DIY-vs-workshop cost decision, and step-by-step guided repairs. Reading codes and clearing them is free, always.",
      },
      { property: "og:type", content: "website" },
      { property: "og:url", content: SITE_ORIGIN },
      { property: "og:site_name", content: "iMechanic" },
      /* M1 — the share card. Until now every shared link rendered as a blank
         rectangle. `og:image` must be ABSOLUTE (crawlers drop relative paths),
         hence the constant in `src/lib/site.ts`. The art is generated from the
         real tokens and glyphs by `bun scripts/gen-og.mjs`; `design/og.svg` is
         its vector master. Twitter needs its own pair plus the card type, or it
         falls back to a small thumbnail. */
      { property: "og:image", content: OG_IMAGE_URL },
      { property: "og:image:width", content: OG_IMAGE_WIDTH },
      { property: "og:image:height", content: OG_IMAGE_HEIGHT },
      { property: "og:image:type", content: "image/png" },
      { property: "og:image:alt", content: OG_IMAGE_ALT },
      { name: "twitter:card", content: "summary_large_image" },
      { name: "twitter:title", content: "iMechanic — From fault code to completed repair" },
      {
        name: "twitter:description",
        content:
          "AI root-cause diagnosis, an honest severity verdict, a DIY-vs-workshop cost decision, and step-by-step guided repairs. Reading codes and clearing them is free, always.",
      },
      { name: "twitter:image", content: OG_IMAGE_URL },
      { name: "twitter:image:alt", content: OG_IMAGE_ALT },
      /* iOS home-screen installs (QA defect D16): without these an
         iPhone install opens in Safari chrome instead of standalone.
         `black-translucent` lets our navy pt-safe header own the
         status-bar area. `mobile-web-app-capable` is the modern
         cross-platform equivalent. */
      { name: "mobile-web-app-capable", content: "yes" },
      { name: "apple-mobile-web-app-capable", content: "yes" },
      { name: "apple-mobile-web-app-status-bar-style", content: "black-translucent" },
      { name: "apple-mobile-web-app-title", content: "iMechanic" },
    ],
    links: [
      /* Inter is self-hosted (QA defect D15) — never link fonts from a
         Google domain; the @font-face rules live in app.css. */
      { rel: "stylesheet", href: appCss },
      { rel: "manifest", href: "/manifest.webmanifest" },
      /* Opaque 180x180 — iOS composites transparency onto black (D16). */
      { rel: "apple-touch-icon", sizes: "180x180", href: "/icons/apple-touch-icon.png" },
      /* A4: the tab icon is the engine mark on the navy brand tile — the same
         art as the installed app icon and the in-app brand mark. Both files
         are generated by scripts/gen-icons.mjs straight from `EngineIcon`, so
         the tab, the header and the home-screen tile cannot drift apart. The
         SVG is the one browsers actually use; the .ico is what gets served to
         anything that still asks for /favicon.ico. */
      { rel: "icon", type: "image/svg+xml", href: "/icon.svg" },
      { rel: "icon", href: "/favicon.ico" },
    ],
  }),
  notFoundComponent: NotFound,
  component: RootComponent,
});

/** Styled 404 (QA defect D21). Plain statement of fact, a way back in —
 *  no chrome, so it works for both marketing and app URLs. */
function NotFound() {
  return (
    <main className="flex min-h-dvh flex-col items-center justify-center bg-app-bg px-6 text-center text-fg">
      <p className="text-xs font-semibold uppercase tracking-wider text-fg-subtle">
        404
      </p>
      <h1 className="mt-2 text-2xl font-extrabold tracking-tight">
        This page doesn't exist
      </h1>
      <p className="mt-3 max-w-sm text-sm leading-relaxed text-fg-muted">
        The address may be mistyped, or the page may have moved. Nothing you
        saved is affected.
      </p>
      <div className="mt-6 flex flex-wrap items-center justify-center gap-3">
        <a
          href="/app"
          className="rounded-control bg-chrome px-5 py-3 text-sm font-semibold text-on-chrome transition-colors hover:bg-navy-900"
        >
          Open the app
        </a>
        <a
          href="/"
          className="rounded-control border border-line-strong px-5 py-3 text-sm font-semibold text-fg transition-colors hover:bg-neutral-fill"
        >
          Go to the homepage
        </a>
      </div>
    </main>
  );
}

function RootComponent() {
  return (
    <RootDocument>
      <ServiceWorkerRegistrar />
      <Outlet />
    </RootDocument>
  );
}

/** Registers the app-shell service worker. Client-only, never blocks render.
 *
 * Gated on the production build (QA defect D8) — "is HTTPS" was the wrong
 * gate: the working/dev site is also HTTPS, so the SW installed there and
 * served stale cache-first assets during development. In dev we additionally
 * unregister any SW left behind by an earlier build and drop its caches. */
function ServiceWorkerRegistrar() {
  useEffect(() => {
    if (typeof window === "undefined") return;
    if (!("serviceWorker" in navigator)) return;
    if (!import.meta.env.PROD) {
      // Clean up any stale registration from before this gate existed.
      navigator.serviceWorker
        .getRegistrations()
        .then((regs) => regs.forEach((r) => r.unregister()))
        .catch(() => {});
      if ("caches" in window) {
        caches.keys().then((keys) => keys.forEach((k) => caches.delete(k))).catch(() => {});
      }
      return;
    }

    /* The build id is stamped into the SW URL (QA defect D9): sw.js derives
       its cache name from `?v=`, so every deploy re-installs the worker,
       `activate` fires, and stale caches from previous builds are deleted.
       Without this the literal cache name froze unhashed assets forever. */
    const register = () => {
      navigator.serviceWorker
        .register(`/sw.js?v=${__BUILD_ID__}`, { scope: "/" })
        .catch((err) => {
          console.warn("[iMechanic] service worker registration failed:", err);
        });
    };

    if (document.readyState === "complete") register();
    else {
      window.addEventListener("load", register, { once: true });
      return () => window.removeEventListener("load", register);
    }
  }, []);

  return null;
}

function RootDocument({ children }: { children: ReactNode }) {
  return (
    // suppressHydrationWarning (QA defect D3): the blocking theme script
    // above mutates <html> (data-theme + dark class) before React hydrates,
    // so SSR and first client render intentionally differ on this element.
    // React must not diff it.
    <html lang="en" suppressHydrationWarning {...themeDataAttrs}>
      <head>
        {/* Applies the stored theme before first paint — no flash of the
            wrong theme when someone opens the app at night. Must stay inline
            and blocking; do not move it into a module. */}
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
        <HeadContent />
      </head>
      <body>
        {children}
        <Scripts />
      </body>
    </html>
  );
}